name: secrets_workflows
on:
 workflow_dispatch:
jobs:
 login:
   runs-on: ubuntu_latest
   steps:
   - name: LOGING INTO DOCKER 
     uses: docker./login-action@v2
     with:
       username: ${{secrets.DOCKERHUB_USERNAME}}
       password: ${{secrets.DOCKERHUB_PASSWORD}}
Footer
© 2022 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
